peewee_migrate/migrator.py

@klen, `peewee`'s migrator does not create unique index while adding _unique_ column. I suggest `peewee_migrate` to do it.

Add unique index creation

---

peewee_migrate/migrator.py

The SchemaMigrator `from_database` method wasn't returning the parent super call value.

If not Postgresql/Sqlite, return parent `from_database`

---

peewee_migrate/router.py

Replace error info 'Invalid models module...'  to a better hint.
fix filter arguments at https://github.com/klen/peewee_migrate/edit/develop/peewee_migrate/router.py #57 line

Fix auto create migration

---

.gitignore
peewee_migrate/auto.py
peewee_migrate/cli.py
peewee_migrate/router.py
tests/test_cli.py

This fix isn't very elegant, I'm sure you can come up with something better. The only reason I didn't just use __name__ is that it was possible that you could reference a model before it is defined. One possible way to implement this would be to order the model creation based on it's dependencies, I believe peewee has a function that does this (sort_models_topologically) but I'm not sure if that would work in  all cases. Another approach might be lazy local imports instead of lazily importing the original models. I also had to change the related_name because it was resulting in conflicts given the mixing of migration and original models.

Proposed fix for #14

---

peewee_migrate/cli.py
tests/test_cli.py

This means you can use:
pw_migrate migrate --fake --database=...
Instead of 
pw_migrate migrate --fake text_value_here --database=...
The text value passed for `--fake` was used as a truthy value for [`BaseRouter.run`](https://github.com/klen/peewee_migrate/blob/cbcc6cbdc92348377f74b95cf8c48bd10f9aa37b/peewee_migrate/router.py#L152). Making `--fake` a flag means `True` is passed to `BaseRouter.run` rather than the text value given on the command-line.

Make --fake CLI option a flag

---

peewee_migrate/auto.py

```python
class User(Model):
email = CharField(max_length=50, index=True, unique=True)
```
Causes the migrator to always find an index difference.  The mocked models use field.index = not field.unique, so index will always be false.  An easy fix is to remove index=True in the model definition, but this PR should prevent the issue from occurring in the first place. 
Example excess migration:
```python
def migrate(migrator, database, fake=False, **kwargs):
"""Write your migrations here."""
migrator.drop_index('user', 'email')
migrator.add_index('user', 'email', unique=True)
```

fix index=True and unique=True

---

peewee_migrate/auto.py
tests/test_auto.py

Hi,
First thing, thank you for your work :)
I have noticed that when I define a model with multi column unique key:
```
class Object(pw.Model):
first_name = pw.CharField()
last_name = pw.CharField()
class Meta:
indexes = (
(('first_name', 'last_name'), True),
)
```
and if I use `auto` generate feature: `pw_migrate create --auto .....`, so in generated migration file `indexes` attribute is missing in `Meta` class.
So this PR is about to add this feature to `peewee_migrate`.

include meta indexes attribute to migration

---

peewee_migrate/migrator.py
tests/mocks/postgres.py
tests/test_migrator.py

When attempting to apply a postgres migration, alter column would fail. This is because the object returned by `alter_change_column` is expected to be a `Clause`, but instead is a `Context` object.  It looks like this may have been something that changed between Peewee 2 and 3.
Also, added a postgres migrator test.

Fix postgres change column

---

peewee_migrate/template.txt

Hey bro, the migrations using decimal needs to import ROUND_HALF_EVEN, otherwise, it'll crash

Fixed decimal import

---

peewee_migrate/router.py

load_models is executed only once with the correct result
```
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> from peewee_migrate.router import load_models
>>> 
>>> load_models('tests.test_autodiscover')
{<Model: Object2>, <Model: Object1>, <Model: Model3>, <Model: Object1>, <Model: Model1>, <Model: Object3>, <Model: Object3>, <Model: BaseModel>, <Model: Model2>, <Model: BaseModel>, <Model: Object2>, <Model: Model2>}
>>> 
>>> load_models('tests.test_autodiscover')
set()
>>>
```
I fixed the default assignment of `passed` in router._import_submodules.

Fixed "Default argument value is mutable" in load_models.

---

peewee_migrate/router.py

Signed-off-by: Mateusz Susik <msusik@sigmoidal.io>

removal of a development testing leftover in the auto discovery.

---

peewee_migrate/router.py

Sometimes we create migrations for local development databases but someone adds an invalid import, in this situation the real error is hidden from the developer as only `Can't import models module: True` is returned instead of the real issue: `No module named 'peewee_extra_fields'`. This PR is meant to help prevent others from having to download this library and place it in the editable mode with a debugger in it.. just to find out the library works as expected.

Return useful error when there is an issue with the underlying developers imports.

---

peewee_migrate/migrator.py

The function rename_table call self.migrator.rename_table(model, model) with the same model names:
def rename_table(self, model, **new_name**):
&nbsp;&nbsp;&nbsp;&nbsp;"""Rename table in database."""
&nbsp;&nbsp;&nbsp;&nbsp;del self.orm[model._meta.table_name]
&nbsp;&nbsp;&nbsp;&nbsp;**model._meta.table_name** = **new_name**
&nbsp;&nbsp;&nbsp;&nbsp;self.orm[model._meta.table_name] = model
&nbsp;&nbsp;&nbsp;&nbsp;self.ops.append(self.migrator.rename_table(**model._meta.table_name, new_name**))
&nbsp;&nbsp;&nbsp;&nbsp;return model

Fixes an issue with migrator.rename_table(..)

---

peewee_migrate/cli.py
tests/test_cli.py

I found it quite unhandy that cli requires migration name for rollback operations. The following PR adds ability to rollback by either migration name or by number of migrations.
Like `rollback 5` will rollback 5 last migrations.
Also found an issue that in memory sqlite limits us from fully testing cli in context of previously done migrations. And for some reason `--fake` affects the freshly loaded `router.done`, but it shouldn't. I commented it for now. Not sure if we need to fix it within this PR.

Rollback by number of migrations feature

---

peewee_migrate/cli.py

Fixes issue with `auto-source` param likely caused by click guessing its type from the default value.
If default is a bool, click will expect `BOOLEAN` and will not allow a string, which is what we need.
Changes is in this PR
- change default value of `auto-source` param to None so that click infers `TEXT`. 
cc/ @klen

fix auto-source default

---

peewee_migrate/auto.py
tests/test_auto.py

Fixes #202 
With this PR, auto migrations will work correctly for models with self-referencing foreign keys. Right now, applying the migration fails because of `KeyError` (model is not yet in `migrator.orm` dict)
cc/ @klen

Fix self-referencing foreign keys

---

peewee_migrate/__init__.py
peewee_migrate/cli.py

Let applications that use peewee_migrate to control their output. https://docs.python.org/3/library/logging.handlers.html#nullhandler
Fixes #216
Note: the code just expresses the intent to start the discussion. It may need to be tweaked before the merge.
cc/ @klen

fix(logging): don't write to stderr when used as a library

---

peewee_migrate/router.py
peewee_migrate/template.py

Fixes #
When bundling using Nuitka or PyInstaller, the template.txt is not bundled which leads to a runtime error `FileNotFoundError`.
Changes in this PR
- Use a Python file with a constant instead of `template.txt`
- Removed the `template` cached property since it is now a constant
cc/ @klen

fix: python template for bundling

---

peewee_migrate/migrator.py
tests/conftest.py
tests/test_migrator.py

After 0.14.0 it's not possible to change field constraint in SQLite using peewee_migrate.
This commit returns 0.14.0 behavior for Migrator.change_fields()
change_field() replaces existing field with new one with the same name
added unit test
- 
cc/ @klen

Support fields constrains change

---

peewee_migrate/migrator.py

- removing of double unique index creation, as it is already created in playhouse - https://github.com/coleifer/peewee/blame/f107a90897a21c9e4ef1aa43bd61a54ceb5e943f/playhouse/migrate.py#L345
- without this commit the behavior is:
```
2023-08-04 11:53:51,517 20748 9968 N/A INFO peewee_migrate Migrate "123_add_uuid"
2023-08-04 11:53:51,517 20748 9968 N/A INFO peewee_migrate add_column ('some_table', 'uuid', <SomeField: SomeModel.uuid>)
2023-08-04 11:53:51,517 20748 9968 N/A DEBUG peewee ('ALTER TABLE `some_table` ADD COLUMN `uuid` BINARY(16)', [])
2023-08-04 11:53:51,521 20748 9968 N/A DEBUG peewee ('CREATE UNIQUE INDEX `some_table_uuid` ON `some_table` (`uuid`)', [])
2023-08-04 11:53:51,528 20748 9968 N/A INFO peewee_migrate add_index ('some_table', ('uuid',))
2023-08-04 11:53:51,528 …
```

bugfix: removed double creation of unique index
